### ISSUE TITLE
If the output file already exists, the server is appended to that file instead of overwriting it.

### ISSUE THREAD

**Issue by Badel2** [marblenix/minecraft_downloader#10]
**Describe the bug**
I just noticed that some of my server jar files are suspiciously big (one of them 180MB!). After some debugging, I think it is because if the output file already exists, the server is appended to that file instead of overwriting it.

**To Reproduce**
Please enter the command used and any environment variables:
Please also include the full output of the command

1. Command: 
```
bdl@deb:/tmp$ minecraft_downloader --version=1.18-rc1
Found Minecraft version "1.18-rc1"
Saving minecraft .jar as minecraft_server_1.18-rc1.jar
Downloading 46323515 bytes from https://launcher.mojang.com/v1/objects/81a2baf05f8f5bda41fac1542e7cc9d937bff41b/server.jar...
bdl@deb:/tmp$ ls -l minecraft_server_1.18-rc1.jar 
-rw-r--r-- 1 bdl bdl 46323515 nov 25 23:18 minecraft_server_1.18-rc1.jar
bdl@deb:/tmp$ minecraft_downloader --version=1.18-rc1
Found Minecraft version "1.18-rc1"
Saving minecraft .jar as minecraft_server_1.18-rc1.jar
Downloading 46323515 bytes from https://launcher.mojang.com/v1/objects/81a2baf05f8f5bda41fac1542e7cc9d937bff41b/server.jar...
bdl@deb:/tmp$ ls -l minecraft_server_1.18-rc1.jar 
-rw-r--r-- 1 bdl bdl 92647030 nov 25 23:18 minecraft_server_1.18-rc1.jar
```
2. Environment (env | grep MINECRAFT):
```
```

I think the easiest way to fix this would be to set `append(false)` here:

https://github.com/marblenix/minecraft_downloader/blob/3339014ea1acfdad6a29ae645389a34cbc5acaa3/src/main.rs#L145

Or ideally skip the download if the output file matches the expected size and hash.

**Comment by marblenix** [comment]
Thank you for the bug report! The new version is live.
