### ISSUE TITLE
Failed to compile from source

### ISSUE THREAD

**Issue by Badel2** [marblenix/minecraft_downloader#8]
Hi, I wanted to compile this project from source but it shows an error:

Command: 
```
git clone https://github.com/marblenix/minecraft_downloader
cd minecraft_downloader
cargo install --path .
```

Output:

```
error[E0433]: failed to resolve: could not find `runtime` in `tokio`
   --> src/main.rs:203:12
    |
203 |     tokio::runtime::Runtime::new()
    |            ^^^^^^^ could not find `runtime` in `tokio`

error: aborting due to previous error
```

Rust version:

```
$ rustc --version
rustc 1.46.0 (04488afe3 2020-08-24)
```

**Comment by Badel2** [comment]
Fixed it by looking at `.travis.yml`, and running:

    cargo build --verbose --all --release
    ./target/release/minecraft_downloader

Not sure why `cargo install` doesn't work.

**Comment by marblenix** [comment]
Thank you for your interest in my fun side projects 😁

It looks like install is running some extra checks than simply building. I'll get to work on making install work as well as build.

**Comment by Badel2** [comment]
Works fine now, thanks!
